satwikkansal/wtfpython

- README.md
Fixed the output of `isinstance(False, float)` and changed `False` to `True` to match `isinstance(True, int)`
> Fixed wrong output of `isinstance(False, float)`

- mixed_tabs_and_spaces.py
flake8 testing of https://github.com/satwikkansal/wtfpython on Python 3.6.2
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./mixed_tabs_and_spaces.py:5:18: E999 TabError: inconsistent use of tabs and spaces in indentation
return sum_so_far
^
```
> Mark TabError as noqa to silence linters on Python 3

- README.md
As in the title. There was a small typo within the `For what?` example.
> Fix typo in the "For what?" example

- README.md
Made the text say it depends on class, and rest of explanation talk of lists, not objects.
> a+=b vs a=a+b : clarify the difference is not universal

- README.md
Just a minor typo.
On a cyclic list, ```some_list is some_list[0]``` return  ```True``` and not ```[[...]]```
> Fix typo, expression output True and not [[...]]

- README.md
Closes https://github.com/satwikkansal/wtfpython/issues/32
> Add new snippet: Yielding None

- README.md
Hi,
I though of contributing to your great collection of python tricks.  The example I included is iterating a generator expression after updating the iterable of generator. The trick here is updating the iterable using normal assignment vs slice assignment, which will produce different results.
Also please suggest a cool title if you can :)
Thanks
Sohaib
> Generator with Slice assignment trick

- .travis.yml
The repo switch would need to be turned on at https://travis-ci.com/satwikkansal/wtfpython to enable free automated testing of all code changes.
> Add automated testing using Travis CI

- README.md
the link that points to the issues in the README was pointing to the repository link https://github.com/satwikkansal/wtfpython/ so I changed it to point to the new issue link https://github.com/satwikkansal/wtfpython/issues/new
> Fix issue creating link

- README.md
Remove the sentence about call by reference / value and replacete it by an explanation about reassignation.
closes #163
> Fix explanation for 6th example of "Needles in a Haystack"

- README.md
The example showing how using None as a default argument is used
instead of a mutable default argument had reversed logic.  It would
set default_arg to [] whenever the caller passed a non-None argument.
> Fixed logic error in "Beware of default mutable arguments!"

- README.md
The example of the use of backslash to escape a double-quote makes
more sense when used inside a double-quoted string. If the string is
quoted with single quotes, one could of course just write 'wt"f'
withouth requiring any escaping.
> Clarify for quoting examples

- README.md
I thought that the explanation for "'something' is (not None)" could
be a little more explicit.
> Extend the explanation of the "is not ..." section

- CONTRIBUTORS.md
- README.md
I tested on Python 3.6, 3.7 and 3.8. On Python 3.5, sizes do not change - which suggests 3.5 doesn't have key sharing, although it did have, I think (the PEP was introduced between 3.3 and 3.4). And Python 2 is irrelevant, of course.
Closes: #210
> Add "bloating instance dicts" section

- CONTRIBUTORS.md
- README.md
@satwikkansal , 
> That's interesting. We can possibly add following based on the SO answer you linked,
> 
> ```python
> c1.__str__ == c2.__str__  # False
> c1.__dict__.__str__ == c2.__dict__.__str__ # True ??
> ```
I decided to skip this particular snippet, because:
1. The explanation is already quite long :sweat_smile: And I think explaining these bits about descriptors and differences between `classmethod`, `staticmethod` etc is more useful for Python developers, compared to understanding the (funny) `c1.__dict__.__str__` o.O
2. It irrelevant in modern Python versions (does not reproduce on 3.8)
Closes: #233
> Add section on methods equality and identity

- CONTRIBUTORS.md
- README.md
Hello @satwikkansal!
Refer to issue: #252. I've finished the Spanish translation (wrote 1 week on the issue but it turns out I'm a few days late 😅). Nonetheless, the translation is completed.
**Things I did:**
- Translated all content from English to Spanish from the files `README.md`, `CONTRIBUTING.md` and `CONTRIBUTORS.md`.
- Replaced some links with its Spanish translation mirror (most docs.python.org links and some wikipedia links).
- Translate **only** the comments from the code snippets.
The repository: [JoseDeFreitas/wtfpython-es](https://github.com/JoseDeFreitas/wtfpython-es) (on `master` branch).
**This pull request:**
- Added the reference in the [README.md](https://github.com/satwikkansal/wtfpython/blob/master/README.md) file.
- Added myself in the …
> Add Spanish translation

- irrelevant/notebook_generator.py
- wtfpython-pypi/wtf_python/main.py
Documented various functions that we found particularly lacking of docstrings.
> Added docstrings to several undocumented functions

- README.md
Update the link to Python docs that was incorrect, and adds parenthesis that makes the conditional statements easier to understand.
> Update link and add parenthesis to chained operators section

- README.md
Added a link to the Russian version. Russian language is used not only in Russia, but also in C.I.S. countries: 
- Belarus
- Ukraine
- Kazakhstan
- Armenia
For those who have difficulty reading in English there is a Russian version of this repository.
> Update README.md, Added a link to the Russian version

- README.md
The ideia is pretty much improve the explanation of why `'a'[0][0][0][0][0]` is syntactically correct.
> Improve string indexing result explanation

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/new_snippet.md
- .github/ISSUE_TEMPLATE/translation.md
- .github/PULL_REQUEST_TEMPLATE/new_snippet.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/PULL_REQUEST_TEMPLATE/translation.md
- CONTRIBUTING.md
Fixes #269 
Request review from @satwikkansal
> #269: Update contributing and add pr issue templates

- .github/workflows/pr.yml
- .markdownlint.yaml
> #371: Create temp file with changed LOC for lint CI action
