satwikkansal/wtfpython

- README.md
Doing `True == False` won't assign `False` to `True`.
> Fix the True assignment example.

- README.md
[What happens when you try to delete a list element while iterating over it](https://stackoverflow.com/questions/45946228/what-happens-when-you-try-to-delete-a-list-element-while-iterating-over-it)
> add link to a more specific Stack Overflow thread

- README.md
* Add another function `add_bytes_with_plus` actually illustrating
quadratic behavior for the `+=` operator.
* Add explaination for linear behavior due to `+=` optimizations
in case of strings.
* Change the order of examples (move string interning example just
before the giant string example).
Closes https://github.com/satwikkansal/wtfpython/issues/38
> Update Example: Let's make a giant string

- README.md
Closes https://github.com/satwikkansal/wtfpython/issues/40
> Add new snippet: Half quoted triple strings

- code-of-conduct.md
Added a code of conduct in order to outline the expectations surrounding the conduct of the contributors to this project.
> Added a contributor's code of conduct.

- README.md
* Tweaked a line break so a section number was correctly formatted
* Tweaked grammar to be slightly more natural
Hello!  I started this pull request because the formatting was snafued there, but also made a tiny tweak to the wording when I was there!
Thanks for a very entertaining and educational page.
> Format and grammar tweak

- CONTRIBUTING.md
- CONTRIBUTORS.md
siginificant -> significant
greatful -> grateful
> Fixed critical issue

- README.md
[Deep down we're all the same](https://github.com/Vibhu-Agarwal/wtfpython#-deep-down-were-all-the-same-): Input-Output of the explanation code
> Fixed input-output of 4th example explanation code

- README.md
It is easy to overlook the () in that appending operation, I propose adding a short comment.
> make the function *call* more visible

- README.md
I was WTFing for way too long until I realised that the results were displayed in opposite order of the if/else statement.
> match order of display to if/else order

- wtfpython-pypi/wtf_python/main.py
if not set encoding attr,there maybe have some exceptions when open reading.
> add encoding attr for open reading

- irrelevant/generate_contributions.py
Identity is not the same thing as equality in Python.
$ __[flake8](http://flake8.pycqa.org)  . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
if resp.status_code is 200:
^
1     F632 use ==/!= to compare str, bytes, and int literals
1
```
> Use ==/!= to compare str, bytes, and int literals

- README.md
WTF case based on Raymond's prank https://twitter.com/raymondh/status/1131103570856632321
> Add space-invader operator case

- README.md
Change URL parameter from `hastags` to  `hashtags`.
> Make hashtags in Twitter link work

- README.md
Fix incorrect input for `Name Mangling`.
> Fixed example input error

- README.md
> Wild imports typo

- README.md
Noticed a minor spelling error while reading through this fantastic
document.
> Fix spelling (found -> find)

- README.md
Assignment expressions are immediately evaluated and printed by the Python REPL.
> Add two missing outputs in the walrus examples

- README.md
Tell me if you think anything is missing in the explanation.
I didn't add the `Example ID` thing because I don't know how are these UUIDs generated.
Closes: #208
> Add "dict lookup performance" section

- CONTRIBUTING.md
- CONTRIBUTORS.md
- README.md
I did not have to make many changes to what was already present with `global`. The link to the blog also is the same since it also explains `nonlocal`.
Also, this is something I did not understand, you can modify this bit before merging if at all this PR is merged.
> #193 The out of scope variable, nonlocal

- README.md
> 📝 Fixed simple typos

- README.md
The wording is a little bit different to what I proposed in the issue (#255) but I feel like this is more cohesive.
> Update explanation for All-true-ation

- README.md
Hashable has been move.
https://docs.python.org/3/library/collections.abc.html#collections.abc.Hashable
> fix: Hashable import

- README.md
1. It seems to me `leisurelicht`'s repo is not the newer Chinese translation, however, we're not dismissing his/her effort
2. The links modified here are not exhaustive, and I haven't tried to find all of them
> Fix some outdated links

- README.md
Minor fix to main README after completing Russian translation
> Change link to Russian translation (follow up to PR #325)

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/new_snippet.md
- .github/ISSUE_TEMPLATE/translation.md
@satwikkansal , please review hot fixes for issue templates. Also I don't see pull request templates available, could you also check them?
> #269: Change issues link and fix typos in Github issue templates

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/new_snippet.md
- .github/ISSUE_TEMPLATE/translation.md
- .github/PULL_REQUEST_TEMPLATE/common.md
- .github/PULL_REQUEST_TEMPLATE/new_snippet.md
- .github/PULL_REQUEST_TEMPLATE/translation.md
> Rename common PR template, fix links in PR and issue templates
